/* 新色示範檔 — 全虛構、21+、價格待確認 */
window.XINSE_DATA = {
  cities: [
    { id: "all", name: "全區", code: "ALL" },
    { id: "tpe", name: "台北", code: "TPE" },
    { id: "txg", name: "台中", code: "TXG" },
    { id: "hsz", name: "新竹", code: "HSZ" },
    { id: "tao", name: "桃園", code: "TAO" },
    { id: "nwt", name: "新北", code: "NWT" },
    { id: "khh", name: "高雄", code: "KHH" },
    { id: "tnn", name: "台南", code: "TNN" },
    { id: "cyi", name: "嘉義", code: "CYI" },
    { id: "yun", name: "雲林", code: "YUN" },
    { id: "ila", name: "宜蘭", code: "ILA" },
    { id: "mia", name: "苗栗", code: "MIA" },
    { id: "chw", name: "彰化", code: "CHW" },
    { id: "nan", name: "南投", code: "NAN" },
    { id: "kel", name: "基隆", code: "KEL" },
    { id: "hua", name: "花蓮", code: "HUA" },
    { id: "ttt", name: "台東", code: "TTT" },
    { id: "pen", name: "澎湖", code: "PEN" },
    { id: "pif", name: "屏東", code: "PIF" },
    { id: "kin", name: "金門", code: "KIN" }
  ],
  profiles: [
    {
      id: "s01",
      protocol: "XS-S01",
      name: "林予安",
      type: "select",
      typeLabel: "認證檔期",
      age: 28,
      height: 165,
      city: "tpe",
      cityName: "台北",
      mode: "定點",
      env: "飯店禮賓",
      lang: "中文、英語",
      claim: "商務後的低聲時段",
      image: "img/portrait-s01.jpg?v=cover2",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["時長", "對話節奏", "餐敘後時段"],
      bounds: ["錄影", "站外轉帳", "未預約到訪", "酒後"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "予安把檔期當一份對齊過的協議：準時、少廢話、燈光固定。適合談完事、需要把節奏放慢的夜。示範檔，非真實可約對象。"
    },
    {
      id: "s02",
      protocol: "XS-S02",
      name: "高森葵",
      type: "select",
      typeLabel: "認證檔期",
      age: 26,
      height: 168,
      city: "txg",
      cityName: "台中",
      mode: "定點",
      env: "飯店",
      lang: "中文、日語",
      claim: "俐落、少修飾",
      image: "img/portrait-s02.jpg?v=cover2",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["時長", "靜音時段"],
      bounds: ["錄影", "站外轉帳", "第三人到場"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "葵把「準」放在第一位。進房前對過規格，過程不即興加項。示範檔。"
    },
    {
      id: "s03",
      protocol: "XS-S03",
      name: "黎澄",
      type: "select",
      typeLabel: "認證檔期",
      age: 32,
      height: 170,
      city: "khh",
      cityName: "高雄",
      mode: "定點",
      env: "飯店禮賓",
      lang: "中文",
      claim: "輕熟、低語調",
      image: "img/portrait-s03.jpg?v=cover2",
      scene: "img/interior-hotel.jpg",
      open: false,
      negotiable: ["時長", "只談、不延長"],
      bounds: ["錄影", "臨時改地點", "酒後"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "澄的檔只開預先排定的夜。現況標為未開放，用來示範失敗態。示範檔。"
    },
    {
      id: "t01",
      protocol: "XS-T01",
      name: "周寧",
      type: "studio",
      typeLabel: "獨立工坊",
      age: 29,
      height: 162,
      city: "tpe",
      cityName: "台北",
      mode: "工坊",
      env: "私人工作室",
      lang: "中文",
      claim: "慢節奏舒壓工坊",
      image: "img/portrait-t01.jpg?v=cover2",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["60／90 分時長", "只做舒壓流程"],
      bounds: ["錄影", "站外轉帳", "未預約到訪"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "工坊在住宅區近公共停車。寧把手機靜音、時間做滿。自介偏長是工坊檔的習慣。示範檔，地址不公開。"
    },
    {
      id: "t02",
      protocol: "XS-T02",
      name: "許沐",
      type: "studio",
      typeLabel: "獨立工坊",
      age: 34,
      height: 160,
      city: "hsz",
      cityName: "新竹",
      mode: "工坊",
      env: "獨立預約",
      lang: "中文、英語",
      claim: "對話感、少表演",
      image: "img/portrait-t02.jpg?v=cover2",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["時長", "只聊天的短檔"],
      bounds: ["錄影", "臨時加時不通知"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "沐接科學園區節奏的晚間檔，提前一天確認。示範檔。"
    },
    {
      id: "t03",
      protocol: "XS-T03",
      name: "南君",
      type: "studio",
      typeLabel: "獨立工坊",
      age: 27,
      height: 167,
      city: "tnn",
      cityName: "台南",
      mode: "工坊",
      env: "私人時段",
      lang: "中文",
      claim: "少話題、準時結束",
      image: "img/portrait-t03.jpg?v=cover2",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["時長"],
      bounds: ["錄影", "酒後", "未預約"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "君的工坊不聊天室延續。檔期結束就結束。示範檔。"
    },
    {
      id: "f01",
      protocol: "XS-F01",
      name: "艾拉",
      type: "signal",
      typeLabel: "限時訊號",
      age: 26,
      height: 163,
      city: "tao",
      cityName: "桃園",
      mode: "短期",
      env: "飯店",
      lang: "中文、英語",
      claim: "本週短期檔",
      image: "img/portrait-f01.jpg?v=cover2",
      scene: "img/interior-signal.jpg",
      open: true,
      negotiable: ["時長"],
      bounds: ["錄影", "站外轉帳"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "機場廊帶的短檔示範。訊號類不保證續週。示範檔。"
    },
    {
      id: "f02",
      protocol: "XS-F02",
      name: "薇拉",
      type: "signal",
      typeLabel: "限時訊號",
      age: 30,
      height: 169,
      city: "nwt",
      cityName: "新北",
      mode: "巡迴",
      env: "北北基移動",
      lang: "中文",
      claim: "北北基巡迴",
      image: "img/portrait-f02.jpg?v=cover2",
      scene: "img/interior-signal.jpg",
      open: true,
      negotiable: ["城市（北北基）", "時長"],
      bounds: ["錄影", "臨時改縣市出北北基"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "薇拉的訊號綁在移動，不在固定房間。邀約前先對城市。示範檔。"
    },
    {
      id: "f03",
      protocol: "XS-F03",
      name: "夏禾",
      type: "signal",
      typeLabel: "限時訊號",
      age: 27,
      height: 164,
      city: "tnn",
      cityName: "台南",
      mode: "週末限定",
      env: "飯店",
      lang: "中文",
      claim: "週末限定",
      image: "img/portrait-f03.jpg?v=cover2",
      scene: "img/interior-signal.jpg",
      open: true,
      negotiable: ["週五至日"],
      bounds: ["平日邀約", "錄影"],
      plan: "1s2500/30min  2s3500/60min",
      bio: "只開週末。平日送出會落到未開放。示範檔。"
    }
  ],
  reports: {
    s01: [
      { name: "會員 · 示範", time: "2026-08-22", text: "準時、對話短、規格和頁面一致。" },
      { name: "會員 · 示範", time: "2026-08-11", text: "飯店動線清楚，沒有額外推銷。" }
    ],
    t01: [
      { name: "會員 · 示範", time: "2026-08-18", text: "工坊安靜，時間有做到。" },
      { name: "會員 · 示範", time: "2026-07-30", text: "節奏慢，適合不想被催的時段。" }
    ],
    f02: [
      { name: "會員 · 示範", time: "2026-08-25", text: "先對了城市再出發，沒有改點。" }
    ]
  }
};
