/* 尚豪檔期 — 文字與肖像來自來源站名單 */
window.XINSE_DATA = {
  contact: {
    line: "",
    telegram: ""
  },
  cities: [
    { id: "all", name: "全部" },
    { id: "tpe", name: "台北中山區" },
    { id: "nkn", name: "南崁區(熟客限定)" },
    { id: "tao", name: "桃園區" },
    { id: "zli", name: "中壢區" }
  ],
  profiles: [
    {
      id: "s01",
      protocol: "XS-S01",
      name: "熙熙",
      type: "select",
      typeLabel: "認證檔期",
      age: 22,
      height: 162,
      weight: 49,
      cup: "D 真奶",
      city: "tao",
      cityName: "桃園區",
      mode: "定點",
      env: "大豐路",
      lang: "中文",
      claim: "無毛白虎控必選",
      image: "img/portrait-s01.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "水中蕭", "無套吹", "舔蛋", "奶洗", "無毛品鮑", "69", "冰火", "奶推", "奶悶臉", "奶炮", "按摩", "屁推"],
      bounds: ["加強服務需提前告知", "限選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "入珠 +500", "口爆 +500", "2+1（150/3s）", "3+1（200/4s）", "5+3 包夜（480/6s）"],
      plan: "2700/40/1s　3000/60/1s　3600/60/2s　4600/90/2s 送絲襪",
      bio: "年輕真 D 奶，敏感多汁。全身光滑細緻、能騷能蕩。水中吹簫、奶炮，帝王式享受。敏感水多耐督，反應真實。"
    },
    {
      id: "s02",
      protocol: "XS-S02",
      name: "璇璇",
      type: "select",
      typeLabel: "認證檔期",
      age: 23,
      height: 166,
      weight: 50,
      cup: "E 柔軟",
      city: "tao",
      cityName: "桃園區",
      mode: "定點",
      env: "中正路",
      lang: "中文",
      claim: "高挑大奶控必選",
      image: "img/portrait-s02.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "足交", "艷舞", "冰火", "按摩", "奶炮", "盡情品鮑", "69", "奶悶臉", "奶推", "水中蕭", "無套吹", "舔蛋", "奶洗"],
      bounds: ["加強服務需提前告知", "可選 2 項加強", "2+1 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "入珠 +500", "情趣玩具(自備新品) +500", "2+1（150/3s）"],
      plan: "2700/40/1s　3000/60/1s　3600/60/2s　4600/90/2s 送絲襪",
      bio: "飢渴淫蕩、天生甜美。敏感濕潤、高潮會抖。主動挑逗，腰力足，水多又緊實。"
    },
    {
      id: "s03",
      protocol: "XS-S03",
      name: "琳琳",
      type: "select",
      typeLabel: "認證檔期",
      age: 23,
      height: 165,
      weight: 50,
      cup: "F 真奶",
      city: "tao",
      cityName: "桃園區",
      mode: "定點",
      env: "桃園後站",
      lang: "中文",
      claim: "超強紅牌回歸",
      image: "img/portrait-s03.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（衛生狀況佳）", "足交", "水中吹簫", "舔蛋", "奶推", "豪邁深喉", "奶炮", "奶滑洗", "女友親", "按摩", "冰火", "自慰秀", "屁推", "毒龍", "69", "盡情品鮑", "奶洗臉", "無套吹"],
      bounds: ["加強服務需提前告知", "可選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "情趣玩具（全新）+500", "入珠 +500", "顏射 +500", "攝影不露臉 +1000", "2+1（150/3s）", "3+1（200/4s）", "5+3 包夜（480/6s）"],
      plan: "2800/40/1s　3100/60/1s　3700/60/2s　4700/90/2s 送絲襪",
      bio: "回沖首選。白皙大奶、騷勁十足，主動勾引。真奶胸型漂亮，深喉含到底。水中簫、奶炮夾、奶滑洗樣樣伺候。"
    },
    {
      id: "s04",
      protocol: "XS-S04",
      name: "慈慈",
      type: "select",
      typeLabel: "認證檔期",
      age: 24,
      height: 160,
      weight: 50,
      cup: "D 真奶",
      city: "tao",
      cityName: "桃園區",
      mode: "定點",
      env: "復興路",
      lang: "中文",
      claim: "騷女服務控必選",
      image: "img/portrait-s04.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "水中蕭", "無套吹", "舔蛋", "奶洗", "奶悶臉", "自慰秀", "奶炮", "冰火", "無毛品鮑", "69", "奶推", "按摩"],
      bounds: ["加強服務需提前告知", "限選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "入珠 +500", "口爆 +500", "顏射 +500", "2+1（150/3s）", "3+1（200/4s）", "5+3 包夜（480/6s）"],
      plan: "2800/40/1s　3100/60/1s　3700/60/2s　4700/90/2s 送絲襪",
      bio: "深喉吞噬、吸舔含頂到底。敏感濕潤、高潮會抖。主動挑逗，腰力足，水多又緊實。"
    },
    {
      id: "s05",
      protocol: "XS-S05",
      name: "薔薔",
      type: "select",
      typeLabel: "認證檔期",
      age: 23,
      height: 155,
      weight: 43,
      cup: "C 真奶",
      city: "zli",
      cityName: "中壢區",
      mode: "定點",
      env: "中原夜市",
      lang: "中文",
      claim: "白皙淫騷服務必選",
      image: "img/portrait-s05.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "無套吹", "奶悶臉", "舔蛋", "奶炮", "角色扮演", "艷舞", "奶推", "冰火", "盡情品鮑", "69", "屁推", "按摩", "水中蕭", "奶洗"],
      bounds: ["加強服務需提前告知", "限選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "情趣玩具(自備新品) +500", "攝影不露臉 +1200", "特殊服務 +1500", "顏射 +500", "2+1（150/3s）", "3+1（200/4s）"],
      plan: "2700/40/1s　3000/60/1s　3600/60/2s　4600/90/2s 送絲襪",
      bio: "可愛正妹、小隻馬。嫩膚緊穴、柔軟巨乳、粉色內裝。敏感易濕，多重服務解鎖。"
    },
    {
      id: "s06",
      protocol: "XS-S06",
      name: "大大",
      type: "select",
      typeLabel: "認證檔期",
      age: 24,
      height: 166,
      weight: 50,
      cup: "F 柔軟",
      city: "zli",
      cityName: "中壢區",
      mode: "定點",
      env: "中原夜市",
      lang: "中文",
      claim: "豪乳巨奶控必選",
      image: "img/portrait-s06.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      gallery: ["img/gallery-3p.jpg?v=akx1"],
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "無套吹", "奶悶臉", "舔蛋", "奶炮", "無毛品鮑", "69", "冰火", "奶推", "水中蕭", "奶洗", "足交", "按摩", "角色扮演", "艷舞", "屁推"],
      bounds: ["加強服務需提前告知", "限選 2 項加強", "2+1／3+1 打槍須至少消費一節"],
      extras: ["絲襪 +100", "毒龍 +200", "入珠 +500", "情趣衣 +100", "自慰秀 +300", "情趣玩具(自備新品) +500", "攝影不露臉 +1200", "2+1（150/3s）", "3+1（200/4s）", "雙飛 3P 與莎莎：60 分 $6000／$7000；90 分 2s $9200"],
      plan: "2700/40/1s　3000/60/1s　3600/60/2s　4600/90/2s 送絲襪",
      bio: "大 F 奶、敏感多汁。水中吹簫、奶炮，帝王式享受。可與莎莎雙飛 3P（1 王 2 后）。"
    },
    {
      id: "s07",
      protocol: "XS-S07",
      name: "莎莎",
      type: "select",
      typeLabel: "認證檔期",
      age: 24,
      height: 164,
      weight: 49,
      cup: "D 柔軟",
      city: "zli",
      cityName: "中壢區",
      mode: "定點",
      env: "中原夜市",
      lang: "中文",
      claim: "淫娃騷姬控必選",
      image: "img/portrait-s07.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      gallery: ["img/gallery-3p.jpg?v=akx1"],
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "水中蕭", "無套吹", "舔蛋", "奶洗", "奶悶臉", "自慰秀", "奶炮", "足交", "角色扮演", "艷舞", "冰火", "按摩", "無毛品鮑", "69", "奶推"],
      bounds: ["加強服務需提前告知", "限選 2 項加強", "2+1／3+1 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "情趣玩具(自備新品) +500", "AV 攝影不露臉 +1200", "口爆 +500", "2+1（150/3s）", "3+1（200/4s）", "雙飛 3P 與大大：60 分 $6000／$7000；90 分 2s $9200"],
      plan: "2700/40/1s　3000/60/1s　3600/60/2s　4600/90/2s 送絲襪",
      bio: "全身光滑細緻又 Q 彈。能騷能蕩、主動熱情。可與大大雙飛 3P（1 王 2 后）。"
    },
    {
      id: "s08",
      protocol: "XS-S08",
      name: "星星",
      type: "select",
      typeLabel: "認證檔期",
      age: 23,
      height: 160,
      weight: 45,
      cup: "F 柔軟",
      city: "zli",
      cityName: "中壢區",
      mode: "定點",
      env: "中壢",
      lang: "中文",
      claim: "騷妹巨乳控必選",
      image: "img/portrait-s08.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（衛生狀況佳）", "女友親", "奶悶臉", "奶泡", "奶推", "屁推", "無套吹", "盡情品鮑", "69", "水中蕭", "奶洗", "按摩"],
      bounds: ["加強服務需提前告知", "限選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "2+1（150/3s）", "3+1（200/4s）", "5+3 包夜（480/6s）", "特殊服務 +1000", "特殊服務 +1500"],
      plan: "2600/40/1s　2900/60/1s　3500/60/2s　4500/90/2s 送絲襪",
      bio: "大 F 奶、敏感多汁。主動挑逗，高潮會抖不停。水多又緊實。"
    },
    {
      id: "s09",
      protocol: "XS-S09",
      name: "菜菜",
      type: "select",
      typeLabel: "認證檔期",
      age: 23,
      height: 158,
      weight: 48,
      cup: "E 柔軟",
      city: "zli",
      cityName: "中壢區",
      mode: "定點",
      env: "中壢",
      lang: "中文",
      claim: "蘿莉巨乳控必選",
      image: "img/portrait-s09.jpg?v=akx1",
      scene: "img/interior-hotel.jpg",
      open: true,
      negotiable: ["舌吻（衛生狀況佳）", "按摩", "艷舞", "冰火", "舔蛋", "奶炮", "女友親", "無套吹", "奶推", "水中蕭", "奶悶臉", "奶洗", "盡情品鮑", "69", "足交"],
      bounds: ["加強服務需提前告知", "可選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "情趣衣 +100", "情趣玩具(需新品) +500", "特殊服務 +1000", "特殊服務 +1500", "2+1（150/3s）", "3+1（200/4s）", "5+3 包夜（480/6s）"],
      plan: "2800/40/1s　3100/60/1s　3700/60/2s　4700/90/2s 送絲襪",
      bio: "主動挑逗、電動腰力。胸型完美、內裝粉色超緊。真空吸吮，回沖首選。"
    },
    {
      id: "t01",
      protocol: "XS-T01",
      name: "YUKI",
      type: "studio",
      typeLabel: "獨立工坊",
      age: 22,
      height: 165,
      weight: 50,
      cup: "G",
      city: "nkn",
      cityName: "南崁區",
      mode: "熟客限定",
      env: "南崁區(熟客限定)",
      lang: "中文",
      claim: "南崁熟客 · 真實巨乳",
      image: "img/portrait-t01.jpg?v=akx1",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["無套吹", "絲襪愛愛（客自備）", "殘廢澡", "胸推", "臀推", "舌吻", "品鮑", "六九", "豪邁吃屌", "舔蛋", "奶泡", "按摩", "深喉嚨包覆"],
      bounds: ["熟客限定", "2+1／3+1／5+3 限定長鐘", "90 分鐘方案不能加鐘組合"],
      extras: ["特殊服務 +1000", "口爆 +500", "2+1／3+1／5+3"],
      plan: "30/1s/3300　50/1s/4000　60/2s/4500　90/ns/5000",
      bio: "強勢回歸。曾經連包 3 天 3 夜。真實巨乳，服務沒話說。南崁區，熟客限定。"
    },
    {
      id: "t02",
      protocol: "XS-T02",
      name: "寶寶",
      type: "studio",
      typeLabel: "獨立工坊",
      age: "",
      height: 155,
      weight: 43,
      cup: "C 真奶",
      city: "tao",
      cityName: "桃園區",
      mode: "熟客限定",
      env: "桃園",
      lang: "簡單中文",
      claim: "越南妹妹 · 素人第一次",
      image: "img/portrait-t02.jpg?v=akx1",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["殘廢澡", "帶套做", "無套吹", "女友親", "舌吻（視衛生與氣氛）", "按摩", "69", "品鮑", "奶炮", "胸推", "屁推", "毒龍", "配合客人自備絲襪"],
      bounds: ["熟客限定", "買 2 送 1／買 3 送 1／買 5 送 3 打槍須至少消費一節"],
      extras: ["口爆 +500", "顏射 +500", "買 2 送 1（2h3s）", "買 3 送 1", "買 5 送 3"],
      plan: "2800/30/1s　2900/40/1s　3300/50/1s　3400/60/1s　3900/60/2s　4400/90/2s",
      bio: "越南妹妹。無牙套、無紋身，簡單中文溝通。素人第一次下海。"
    },
    {
      id: "t03",
      protocol: "XS-T03",
      name: "雨伊",
      type: "studio",
      typeLabel: "獨立工坊",
      age: 20,
      height: 168,
      weight: 43,
      cup: "E 真奶",
      city: "zli",
      cityName: "中壢區",
      mode: "熟客限定",
      env: "中壢",
      lang: "中文",
      claim: "3 點全粉 · 中部精品",
      image: "img/portrait-t03.jpg?v=akx1",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["無套吹", "戴套做", "共浴", "親嘴", "舌吻（衛生）", "品鮑", "69", "舔蛋", "深喉嚨", "水中蕭", "按摩", "奶砲", "胸推", "奶悶臉", "情趣變裝（需自備）", "免費絲襪"],
      bounds: ["熟客限定", "買 3 送 1 打槍須至少消費一節"],
      extras: ["買 3 送 1（30 分=120 分 3s；50 分=200 分 3s）"],
      plan: "A 餐 30/1s/3100　B 餐 50/1s/3600",
      bio: "3 點全粉頂級夢幻色系。高配合度，隱藏版中部精品。可中文。"
    },
    {
      id: "t04",
      protocol: "XS-T04",
      name: "雨貳",
      type: "studio",
      typeLabel: "獨立工坊",
      age: 18,
      height: 166,
      weight: 42,
      cup: "E 真奶",
      city: "zli",
      cityName: "中壢區",
      mode: "熟客限定",
      env: "中壢",
      lang: "簡單中英文",
      claim: "青春款 · 白嫩粉底",
      image: "img/portrait-t04.jpg?v=akx1",
      scene: "img/interior-studio.jpg",
      open: true,
      negotiable: ["無套吹", "戴套做", "共浴", "親嘴", "品鮑", "69", "深喉嚨", "奶泡", "水中蕭", "按摩", "胸推", "奶悶臉", "情趣變裝（需自備）", "免費絲襪"],
      bounds: ["熟客限定", "買 3 送 1／包夜 5+3 打槍須至少消費一節"],
      extras: ["買 3 送 1", "買 5 送 3（50 分=400 分 5s）"],
      plan: "A 餐 30/1s/3300　B 餐 50/1s/4800",
      bio: "18 歲青春款，本人無修飾。白嫩粉底大學生。簡單中英文。"
    },
    {
      id: "f01",
      protocol: "XS-F01",
      name: "蛇蛇",
      type: "signal",
      typeLabel: "限時訊號",
      age: 22,
      height: 161,
      weight: 43,
      cup: "E 柔軟",
      city: "tpe",
      cityName: "台北中山區",
      mode: "空降",
      env: "台北中山區",
      lang: "中文",
      claim: "超強紅牌空降台北",
      image: "img/portrait-f01.jpg?v=akx1",
      scene: "img/interior-signal.jpg",
      open: true,
      negotiable: ["舌吻（口腔不佳不行）", "女友親", "水中蕭", "無套吹", "舔蛋", "奶洗", "奶悶臉", "自慰秀", "奶推", "奶炮", "角色扮演", "艷舞", "冰火", "按摩", "無毛品鮑", "69", "屁推", "足交"],
      bounds: ["加強服務需提前告知", "可選 2 項加強", "2+1／3+1／5+3 打槍須至少消費一節"],
      extras: ["絲襪 +100", "毒龍 +200", "入珠 +500", "情趣衣 +100", "情趣玩具(自備新品) +500", "顏射 +500", "口爆 +500", "吞精（含口爆）+1000", "2+1（150/3s）", "3+1（200/4s）", "5+3 包夜（480/6s）"],
      plan: "2900/40/1s　3200/60/1s　3800/60/2s　4800/90/2s 送絲襪",
      bio: "紅牌回歸，空降台北中山。曾經連包 2 天 2 夜。熱情可甜可騷，水中吹簫、深喉、清槍樣樣伺候。敏感水多耐督，反應真實。"
    }
  ],
  reports: {}
};
